# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cut_c <- function(edges, coord, R) {
    .Call('spatgraphs2_cut_c', PACKAGE = 'spatgraphs2', edges, coord, R)
}

prune_c <- function(edges, level, verbose) {
    .Call('spatgraphs2_prune_c', PACKAGE = 'spatgraphs2', edges, level, verbose)
}

spatcluster_c <- function(x, verbose) {
    .Call('spatgraphs2_spatcluster_c', PACKAGE = 'spatgraphs2', x, verbose)
}

spatgraph_c <- function(coord, type, parameters, verbose) {
    .Call('spatgraphs2_spatgraph_c', PACKAGE = 'spatgraphs2', coord, type, parameters, verbose)
}

